### ISSUE TITLE
Plugins

### ISSUE THREAD

**Issue by codevinsky** [henrikdahl/hyper-statusline#1]
I really like this plugin compared to the alternative. It's clean and simple and I feel like it has a lot of room for a plugin architecture so that devs could add something like:

* vcs status (branch/commit/etc)
* clock
* Machine Status (battery/memory)
* New email status
* Basically whatever you could do in vim/emacs with a status line

Thoughts?

**Comment by henrikdahl** [comment]
@codevinsky Thanks! 👊

I agree, there's definitely room for additions. So far I've only added what I personally use.

I'd need more details on features you'd like to see if you want me to code them in or you could PR them yourself. ✌️

**Comment by henrikdahl** [comment]
@codevinsky, @s2tephen 

Made a version that checks if repo is dirty. What do you guys think about it? Worth including?

![dirty](https://cloud.githubusercontent.com/assets/1430576/21161471/046a725a-c189-11e6-98fe-9fd22c00f0d8.png)

**Comment by s2tephen** [comment]
Looks good to me! What states are you including and what icons will you use to represent them?

**Comment by henrikdahl** [comment]
@s2tephen 

Neat! ✌️

Currently only shows if the repo is dirty or not. Thinking of adding unpulled/unpushed with down/up arrow icons as well.

**Comment by henrikdahl** [comment]
Feedback would be neat on push/pull status.

![push](https://cloud.githubusercontent.com/assets/1430576/21170857/567baeee-c1c8-11e6-9b96-cc28e6107159.png)

**Comment by caesar** [comment]
@henrikdahl I think https://github.com/zeit/hyper/pull/1261 would enable this type of extensibility, no?

**Comment by caesar** [comment]
BTW I like the push/pull status idea, but I haven't worked out what the square with the dot in it means yet…

**Comment by henrikdahl** [comment]
@caesar Great find. I'll definitely update my code once it's in release, which could be a while ✌️

GitHub actually uses the same icon to represent diff, but even so it's not very self explanatory unless you've previously seen it.

I'll add native tooltips for now. I've actually been wanting to add my own custom tooltips but I've simply lacked time.

**Comment by timneutkens** [comment]
@henrikdahl @caesar Landed this in Hyperline dev branch: https://github.com/NickTikhonov/hyperline/tree/develop. Really like the design of this status line + features, maybe we can combine forces? 👍 🎉 Be sure to check https://zeit.chat 😄

**Comment by henrikdahl** [comment]
Just committed a version that now supports pull/push ✌️
