### ISSUE TITLE
Makes Hyper and subprocesses run really slow

### ISSUE THREAD

**Issue by caesar** [henrikdahl/hyper-statusline#10]
I initially thought this was an issue with Hyper, but it turns out disabling `hyper-statusline` solves it.

I have a task which takes about 30 seconds to run when using iTerm (or, it turns out, vanilla Hyper).
When using Hyper with hyper-statusline enabled, the same task takes around **80 seconds** -  in other words, *more than twice as long*.

The task in question is a private (unpublished - in development) Node.js application which is running Prince in a child process to render a PDF from an HTML file.

I haven't tried doing any further debugging – I don't have much time at the moment so I've simply gone back to iTerm for now. But if you have any ideas I will try to check them out, likewise if you want me to test anything else…

**Comment by henrikdahl** [comment]
Could you try the debug-speed branch and check if you see any improvement? ✌️

**Comment by caesar** [comment]
Yes!!! That fixes it! :shipit:

Thanks for the awesome project by the way, you'll probably see some more issues with more ideas in the near future once I've played with Hyper a bit more…

**Comment by caesar** [comment]
I haven't closed this issue because the problem still exists in master, I guess you'll want to leave it open until you merge in the fixes?

**Comment by henrikdahl** [comment]
Ay thanks, glad you like it! 👊

Neat, there's definitely room for additional features.
