### ISSUE TITLE
Don't force new tab to open in current directory

### ISSUE THREAD

**Issue by caesar** [henrikdahl/hyper-statusline#11]
Normally when a new tab is opened in Hyper it opens at the user's home directory, as is conventional in most shells / terminals.

With hyper-statusline installed, new tabs open in the same directory as the PWD in the tab which is focused when Cmd+T is pressed.

Regardless of which behaviour you or I prefer, this type of configuration / behaviour change is outside the scope of a statusline plugin. At the very least, it should be optional, but really it is for a different plugin – better still, a config option in Hyper...

**Comment by henrikdahl** [comment]
I agree 👍

I'll push a commit that changes the behavior in a few. Thanks ✌️

**Comment by caesar** [comment]
Great! Thanks 👍

**Comment by caesar** [comment]
That's much better, thanks!
