### ISSUE TITLE
Option to disable transparent footer

### ISSUE THREAD

**Issue by caesar** [henrikdahl/hyper-statusline#12]
With my theme (solarized dark) I find the footer isn't as visible as I'd like with the default transparency.

I override it by adding this to my Hyper options object:
```js
    css: '.footer_footer { opacity: 1 !important; }',
```

Do you think a simple option to disable it would be useful to others, or am I alone in preferring that it be opaque?

**Comment by henrikdahl** [comment]
I definitely agree that options would be a good addition. I'll add a couple of options after Christmas ✌️

On my way to the Caribbean 🕶

**Comment by caesar** [comment]
Great stuff. Enjoy the Caribbean! 🌴

**Comment by henrikdahl** [comment]
Just pushed an update with config options. Details in readme. If you have any ideas for more options let me know ✌️

**Comment by caesar** [comment]
Cool, looks good! 👍 

One question (I haven't checked this out at all, but it's not clear from the Readme) – what are acceptable values for the `dirtyColor` value? I assume it is CSS colours?

**Comment by henrikdahl** [comment]
Thanks 👊

Indeed, CSS. I was considering either CSS or config colors but ultimately CSS gives you more freedom.
