### ISSUE TITLE
Branch status is only updated on tab switch

### ISSUE THREAD

**Issue by princed** [henrikdahl/hyper-statusline#14]
Is it expected behaviour?

**Comment by henrikdahl** [comment]
Should be updating more reliably now with merged PR #17

Let me know how it works ✌️

**Comment by princed** [comment]
It didn't help, unfortunately 😢

**Comment by henrikdahl** [comment]
What Hyper version and what plugins are you using? ✌️

Right now it updates branch status on title change, window focus, tab switch and enter key button press.

**Comment by princed** [comment]
Looks like it was some Hyper weirdness.
After (accidental) config reset it has started working as expected.
