### ISSUE TITLE
Prettify path

### ISSUE THREAD

**Issue by bevacqua** [henrikdahl/hyper-statusline#15]
Instead of `/Users/bevacqua/dev`, display `~/dev`. You can use [`tildify`](https://github.com/sindresorhus/tildify) for this

**Comment by henrikdahl** [comment]
Good suggestion. I'll add it and also make it a config option. I'm not quite sure which one would be the preferred default as I personally prefer the current implementation. ✌️

**Comment by henrikdahl** [comment]
Just pushed a version that tildifies cwd. I'll look into a config option when I'm back from vacation, still in the Caribbean ✌️

**Comment by bevacqua** [comment]
For a simple example of how to use an option see: https://github.com/bevacqua/hyperterm-working-directory/blob/master/index.js
