### ISSUE TITLE
item_branch not being displayed.

### ISSUE THREAD

**Issue by hemanth** [henrikdahl/hyper-statusline#18]
![issue](https://cloud.githubusercontent.com/assets/18315/21537217/f6a2b790-cdb3-11e6-9daa-da7673dcbf89.gif)

**Comment by henrikdahl** [comment]
What git version are you running?

Also what's your output running `git symbolic-ref --short HEAD` Hyper terminal? ✌️

**Comment by hemanth** [comment]
```
$ git symbolic-ref --short HEAD
master

$ git --version
git version 2.10.1 (Apple Git-78)
```

**Comment by henrikdahl** [comment]
So fetching branch works, appears to be an issue with cwd fetching. Does it display the proper cwd path?

Additionally. Does it work as expected if you run a clean bash terminal setup and only this plugin? ✌️

**Comment by hemanth** [comment]
Works fine after terminal restart, rather than reload; Strange.

**Comment by hemanth** [comment]
<img width="665" alt="screen shot 2016-12-29 at 9 35 38 pm" src="https://cloud.githubusercontent.com/assets/18315/21547874/c78f8428-ce0e-11e6-880e-13ae08e9b0cb.png">
