### ISSUE TITLE
Issues on Hyper Reload

### ISSUE THREAD

**Issue by maxg7** [henrikdahl/hyper-statusline#19]
When reloading Hyper (eg. Cmd-R, not a full reload Shift-Cmd-R) the entire statusline loses context and well as the bash prompt. If you type `clear` the bash prompt comes back but not the statusline. Screenshot attached.

![screen shot 2016-12-29 at 3 52 10 pm](https://cloud.githubusercontent.com/assets/6272740/21554619/fd9fe808-cdde-11e6-91a3-3653c33cf0fc.png)

**Comment by henrikdahl** [comment]
Fixed with @elmasse PR #20 ✌️
