### ISSUE TITLE
[Feature Request] Split Window Status Line

### ISSUE THREAD

**Issue by dbpolito** [henrikdahl/hyper-statusline#21]
Not sure if it was intensional, but when you split the window, you share the status line across all splits, and statusline shows the one you have focusing:

![image](https://cloud.githubusercontent.com/assets/347400/21589428/c731c104-d0d8-11e6-8223-3ed7068d2b0a.png)

I would love to be able to have one status line per split... not sure if everyone prefers that or having a option to have a global one and one per split.

Great work on the plugin btw, loved it. :tada:

**Comment by henrikdahl** [comment]
I'll look into making this a config option asap. Thanks 👊
