### ISSUE TITLE
TypeError Cannot read property 'orange' of undefined

### ISSUE THREAD

**Issue by gilbitron** [henrikdahl/hyper-statusline#22]
Whenever I try and active this plugin I get the following error:

<img width="532" alt="finder - - screen shot 2 jan 2017 3 41 33 pm" src="https://cloud.githubusercontent.com/assets/203882/21592056/f2fc616c-d101-11e6-8e82-816fb633343e.png">

Any ideas?

**Comment by henrikdahl** [comment]
It's because it was relying on an orange color if status line was used in conjunction with my themes. I've just pushed a version that should fix your error ✌️

**Comment by gilbitron** [comment]
Thanks but I'm now getting the same error with "yellow". Any ideas?

**Comment by henrikdahl** [comment]
It appears you're lacking the config colors. What plugins are you using?

**Comment by gilbitron** [comment]
@henrikdahl I removed the "colors" section from my config so I assume I'm just using the defaults.

Plugins:

```
  plugins: [
    'hypercwd',
    'hyper-simple-vibrancy',
    'hyper-simple-highlight-active-session',
//    'hyper-statusline',
  ],
```

**Comment by henrikdahl** [comment]
It's fetching the config colors so if you've removed the default ones and don't use a theme then that's the issue.

Default

```javascript
colors: {
      black: '#000000',
      red: '#ff0000',
      green: '#33ff00',
      yellow: '#ffff00',
      blue: '#0066ff',
      magenta: '#cc00ff',
      cyan: '#00ffff',
      white: '#d0d0d0',
      lightBlack: '#808080',
      lightRed: '#ff0000',
      lightGreen: '#33ff00',
      lightYellow: '#ffff00',
      lightBlue: '#0066ff',
      lightMagenta: '#cc00ff',
      lightCyan: '#00ffff',
      lightWhite: '#ffffff'
    },
```

**Comment by gilbitron** [comment]
Thanks that fixed it 👍
