### ISSUE TITLE
cwd isn't updated when I navigate with rupa/z

### ISSUE THREAD

**Issue by donaldpipowitch** [henrikdahl/hyper-statusline#24]
When I use [rupa/z](https://github.com/rupa/z) for navigation the cwd will not be updated.

I use Mac OS 10.12.2.

**Comment by vinkla** [comment]
I'm also having this issue. I'm using the latest version of macOS and Hyper.

**Comment by henrikdahl** [comment]
It's working for me. Could you give a little more details? ✌️

**Comment by vinkla** [comment]
When I run `z <path>` it doesn't update until next command. Something else I can share?

**Comment by henrikdahl** [comment]
How did you install it?

**Comment by henrikdahl** [comment]
@donaldpipowitch still having this issue?

**Comment by donaldpipowitch** [comment]
@henrikdahl I tested it with 1.6.3 (and hyper@1.1.0), but it doesn't seem to work for me :(

**Comment by henrikdahl** [comment]
@donaldpipowitch 

* Bash or zsh?
* Clean bash/zsh besides Z?
* Installed Z with antigen?
* Only running `hyper-statusline` as plugin for Hyper?

Basically we have to identify why your Z doesn't work with `hyper-statusline` and mine does ✌️

**Comment by donaldpipowitch** [comment]
Thank you for the effort :)
- bash
- Tested with and without a clean bash_profile besides z.
- I don't know antigen :/ I just `source` the `z.sh`.
- Tested with just 'hyper-statusline' and with 'hyperterm-ayu' as plugins.

**Comment by henrikdahl** [comment]
@donaldpipowitch mind trying Z with zsh instead? ✌️

**Comment by donaldpipowitch** [comment]
Looks like `$ exec zsh` and `$ source ~/z.sh` works 🤔 Hmm... time to switch to zsh? 🤔

**Comment by henrikdahl** [comment]
I wonder if this is a Z issue since it works with zsh 🤔

**Comment by henrikdahl** [comment]
@vinkla using bash as well?

**Comment by vinkla** [comment]
@henrikdahl yeah, I'm using Bash.

**Comment by henrikdahl** [comment]
It appears to be a Z issue and not related to `hyper-statusline` so I'm closing this ✌️
