### ISSUE TITLE
Icon for 'git dirty' isn't visible in macOS

### ISSUE THREAD

**Issue by enriquecaballero** [henrikdahl/hyper-statusline#25]
<img width="237" alt="screen shot 2017-01-10 at 2 35 19 pm" src="https://cloud.githubusercontent.com/assets/7918284/21821644/5a198212-d742-11e6-897a-3f74b2541f6f.png">
Also, none of the git stuff seems to work for me in Ubuntu

**Comment by henrikdahl** [comment]
Could you try enforce an update of hyper-statusline by commenting it out, restarting hyper and then comment it back in and restart hyper. Does that fix the git dirty visibility? ✌️

**Comment by enriquecaballero** [comment]
Nope, still nothing :-S

**Comment by henrikdahl** [comment]
What's in console? Can you inspect the element with dev tools to see what icon it's referencing to?

**Comment by enriquecaballero** [comment]
Found it.
<img width="353" alt="screen shot 2017-01-10 at 11 31 59 pm" src="https://cloud.githubusercontent.com/assets/7918284/21835693/133856ca-d78d-11e6-91db-79d5c8466c6e.png">
Problem seems to be with the `background-color` property. Once I set it to 'grey', the dirty icon was visible.

**Comment by henrikdahl** [comment]
Did you by any chance remove your colors in your hyper.js config? Seems it's having issues fetching the config color yellow.

**Comment by enriquecaballero** [comment]
Here's what my `~/.hyper.js` config looks like
```
module.exports = {
  config: {
    fontSize: 13,
    fontFamily: 'Andale Mono, monospace',
    cursorColor: 'rgba(248,28,229,0.8)',
    cursorShape: 'BLOCK',
    foregroundColor: '#fff',
    backgroundColor: '#000',
    borderColor: '#333',
    css: '',
    termCSS: `
      x-screen a {
        color: #F92672;
      }
    `,
    showHamburgerMenu: '',
    showWindowControls: '',
    padding: '12px 14px',
    colors: {
      black: '#000000',
      red: '#ff0000',
      green: '#33ff00',
      yellow: '#ffff00',
      blue: '#0066ff',
      magenta: '#cc00ff',
      cyan: '#00ffff',
      white: '#d0d0d0',
      lightBlack: '#808080',
      lightRed: '#ff0000',
      lightGreen: '#33ff00',
      lightYellow: '#ffff00',
      lightBlue: '#0066ff',
      lightMagenta: '#cc00ff',
      lightCyan: '#00ffff',
      lightWhite: '#ffffff'
    },
    shell: '',
    shellArgs: ['--login'],
    env: {},
    bell: false,
    copyOnSelect: true
  },
  plugins: [
    "hyperterm-monokai",
    "hyper-statusline",
    "hyperlinks",
    "hyperterm-themed-scrollbar",
    "hyper-blink",
    "hyperterm-cursor"
  ],
  localPlugins: []
};
```

**Comment by henrikdahl** [comment]
Did you try just running hyper-statusline to see if it's related to another plugin?

**Comment by enriquecaballero** [comment]
That did it. It doesn't seem to play well with hyperterm-monokai.

**Comment by henrikdahl** [comment]
Just checked `hyperterm-monokai` and it's method for applying the colors to the config appears to break my fetching.
