### ISSUE TITLE
Option to change font size

### ISSUE THREAD

**Issue by chris37879** [henrikdahl/hyper-statusline#26]
Could we get an option to change the font size of the text? My eyes aren't great these days and being able to make the text bigger would be nice.

**Comment by henrikdahl** [comment]
Sure! I'll add it asap ✌️

**Comment by chris37879** [comment]
Thanks!

**Comment by henrikdahl** [comment]
Just pushed a commit with this feature. You can read about the config option in docs ✌️

**Comment by henrikdahl** [comment]
I might expand upon it later so the icons and size of the statusline increases with the font size but unless you make it huge it shouldn't be an issue.

**Comment by ianizaguirre** [comment]
I am not seeing how to change the font size? can I get an example
