### ISSUE TITLE
[Bug] Issues with appearance when scrolling

### ISSUE THREAD

**Issue by alanshortis** [henrikdahl/hyper-statusline#28]
![i 5](https://cloud.githubusercontent.com/assets/3787454/22016867/aec51c24-dc9f-11e6-9bb3-c5342f0fc52f.png)

This happens when scrolling back up the window after running a process with a lot of output.

**Comment by henrikdahl** [comment]
@alanshortis does this only occur when `hyper-statusline` is installed? because it sure looks like it's a hyper thing ✌️

**Comment by alanshortis** [comment]
Hi. I didn't see this issue before installing `hyper-statusline`, and it stopped after removal.

Having just tried it again, I get the same issue, BUT it can be solved by restarting Hyper entirely, not just Reload or Full Reload. This is the same when adding/removing any plugin, so I'll get this logged with Hyper directly.
