### ISSUE TITLE
[Feature request] Add option to change status line font

### ISSUE THREAD

**Issue by codekult** [henrikdahl/hyper-statusline#29]
It would be great if you can adjust the status line font to match with the current font used on terminal.

I would like to know if this is currently possible.

Regards.

**Comment by henrikdahl** [comment]
Just pushed a version that enables you to change fontFamily as a config option.

Enforcing the same font as terminal give less freedom, some might want to use a different font.

You can read about how to set the config option in README ✌️

**Comment by henrikdahl** [comment]
Appears GitHub is down, my latest commits don't show up.

**Comment by ktreese** [comment]
Perhaps I'm missing it, but it seems this is no longer an option?
