### ISSUE TITLE
loss of functionality after switch to zsh

### ISSUE THREAD

**Issue by nhejazi** [henrikdahl/hyper-statusline#30]
I've been using this plugin with Hyper (v1.1.0 currently), recently after a switch to zsh on macOS, the functionality seems to go dead. That is, I've set Hyper to use bash as the default shell, and the plugin works fine; when I switch over to zsh, the plugin stops working. Is zsh not supported? I'm having trouble identifying the source of this error.

**Comment by henrikdahl** [comment]
It supports zsh, I use zsh myself. Could you give a little more information about your entire environment? ✌️

**Comment by nhejazi** [comment]
Ok, good to know. So definitely something on my end then. Basically, I fire up Hyper (v1.1.0) and the plugin works fine when I am in a git repo. If I switch over to zsh, by simply typing zsh, all aspects of the plugin stop working (it doesn't track directory or whether the directory is a git repo at all). I'm happy to provide more information, just not sure what exactly might be relevant. Thanks in advance.

Here's excerpts of my `hyper.js` (only secion that I thought relevant):
```
// the shell to run when spawning a new session (i.e. /usr/local/bin/fish)
    // if left empty, your system's login shell will be used by default
    shell: 'bash',

    // for setting shell arguments (i.e. using interactive shellArgs: ['-i'])
    // by default ['--login'] will be used
    shellArgs: ['--login'],

    // for environment variables
    env: {},

    plugins: [
      "hypercwd",
      "hyperlinks",
      "hyper-blink",
      "hyperterm-tabs",
      "hyperterm-paste",
      "hyperterm-cursor",
      "hyper-statusline",
      "hyperterm-bold-tab",
      "hyper-snazzy" // Snazzy theme
    ],
```

**Comment by henrikdahl** [comment]
Does it work if you actually start with zsh instead of switching in shell?

**Comment by nhejazi** [comment]
Setting `shell: zsh` fixed the problem. Is there some way to start a zsh session and still have the plugin work? I'm not sure what the cause of this error is.

And thanks for the tip re: `hyper-snazzy` and `hyper-statusline`; I've adjusted my `hyper.js` accordingly

**Comment by henrikdahl** [comment]
@nhejazi after some testing this is surely related to hterm or Hyper itself so I'm closing this for now ✌️
