### ISSUE TITLE
Status line positioning/overlay issue with 1.2.0

### ISSUE THREAD

**Issue by brandonweiss** [henrikdahl/hyper-statusline#34]
It looks like there might now be a positioning/overlay issue in the latest version of Hyper (1.2.0).

<img width="730" alt="screen shot 2017-02-15 at 4 44 28 pm" src="https://cloud.githubusercontent.com/assets/4727/23002166/2143ec2a-f39e-11e6-81d4-006bf7875719.png">

**Comment by henrikdahl** [comment]
Yeah, it also broke my `hyper-tabs-enhanced` plugin. I'll update asap ✌️

**Comment by brandonweiss** [comment]
❤️❤️❤️

**Comment by paul-russo** [comment]
My PR #35 corrects this.

**Comment by henrikdahl** [comment]
Class naming convention change was unintentional. It's going to be reverted and most likely end up being 1.2.1 ✌️

**Comment by henrikdahl** [comment]
https://github.com/zeit/hyper/releases/tag/1.2.1

**Comment by henrikdahl** [comment]
@brandonweiss Should work as expected on 1.2.1.

Let me know if you have any issues.

**Comment by joaocunha** [comment]
Same thing happens when used together with [Hyperline](https://github.com/Hyperline/hyperline).

![image](https://user-images.githubusercontent.com/766837/32705717-2ac4e620-c7fe-11e7-9070-697ae79b9703.png)
