### ISSUE TITLE
No git status information shown while on detached commit

### ISSUE THREAD

**Issue by TrevorBurnham** [henrikdahl/hyper-statusline#36]
First off, let me say that I've been enjoying hyper-statusline very much. It's a great addition to my Hyper experience! 🎉 

One request: Currently, when you're on a git branch, hyper-statusline shows the branch name in the lower-right corner. But if you check out a commit that isn't the head of a branch, the corner is blank. I'd enjoy seeing the SHA of the current commit there.

**Comment by henrikdahl** [comment]
@TrevorBurnham Thanks ❤️

I've added your request in the latest commit. It should now display the SHA of current commit in detached checkout as well.

**Comment by TrevorBurnham** [comment]
👏 👏 👏
