### ISSUE TITLE
current folder shows more than just current folder

### ISSUE THREAD

**Issue by chrisdrackett** [henrikdahl/hyper-statusline#37]
I'm getting something like the following:

https://cl.ly/3R2Q2S2K1M0x

**Comment by henrikdahl** [comment]
Interesting. Can I see your `.hyper.js` and your `.zshrc`?

**Comment by chrisdrackett** [comment]
I actually removed both of these files while debugging and I get the same behavior.

**Comment by henrikdahl** [comment]
I can't be much help unless I get more information ✌️

**Comment by chrisdrackett** [comment]
Yeah, just saying I pulled both those out of the running without luck. Where exactly is what is being displayed coming from?

**Comment by henrikdahl** [comment]
It's fetching CWD through this command:

```javascript
const setCwd = (pid) => {
    exec(`lsof -p ${pid} | grep cwd | tr -s ' ' | cut -d ' ' -f9-`, (err, cwd) => {
        curCwd = cwd.trim();
        setBranch(curCwd);
    })
};
```

For some reason it appears to be returning false CWD which to me sounds impossible considering it should affect the entire terminal behavior 🤔

**Comment by chrisdrackett** [comment]
hm, what is pid in this case? (I'm in no way a terminal expert). When I type `pwd` I get the expected result, not sure if this is too simplistic for what this package is trying to do :D

**Comment by chrisdrackett** [comment]
ok, I think I've figured this out. The issue is that my username is `cwd` so the grep is finding *everything*. Not sure if there is an easy fix, and this only really affects me and maybe a very small number of users...
