### ISSUE TITLE
Doesn't work on Windows :(

### ISSUE THREAD

**Issue by stereokai** [henrikdahl/hyper-statusline#4]
Windows 10, Hyper 1.0.0

I'm also getting these errors in the devtools. Although they correspond to the SVG icons, they are straightforward and might shed some light on the issue:

![errors](https://cloud.githubusercontent.com/assets/2685357/21161448/57bc2716-c191-11e6-904c-870fa24d2ef4.PNG)

**Comment by henrikdahl** [comment]
Sadly I can't properly debug this on my own as I don't have Windows.

Do the SVG icons actually reside on that path? Does the status line show up at all?

**Comment by stereokai** [comment]
The correct path is `C:\Users\Tom\.hyper_plugins\node_modules\hyper-statusline\icons` (the slashes are missing), because it seems this: `url('${__dirname}/icons/folder.svg');` isn't working. Maybe it needs to be resolved using nodejs `path` library?

Also the footer is definitely being created, but it isn't being populated.
![footer](https://cloud.githubusercontent.com/assets/2685357/21162026/f7ef464e-c193-11e6-83fa-267d4889a3fa.PNG)

**Comment by stereokai** [comment]
It's weird because logging `__dirname` spews out the correct path string: `C:\Users\Tom\.hyper_plugins\node_modules\hyper-statusline`
However in Chrome (Electron) itself it's always `url('C:\Users\Tom\.hyper_plugins\node_modules\hyper-statusline/icons/folder.svg')`

**Comment by stereokai** [comment]
@henrikdahl and regarding the information not being populated, the command for cwd definitely won't work on Windows :)

**Comment by henrikdahl** [comment]
@stereokai You're definitely right, I wrote that particular code back when Hyper looked to be Mac OS only. I'm gonna look into alternatives ✌️

**Comment by stereokai** [comment]
Sweet, thank you!

**Comment by henrikdahl** [comment]
@stereokai Mind trying the os-windows branch for me? Changed the CWD code but I can't debug myself ✌️

**Comment by stereokai** [comment]
Well, I am definitely getting icons now, but nothing more. Also if I click any of the two icons on the bottom right corner, nothing happens. When I click the folder icon, Hyper freezes and quickly quits (I'm noting this because so far, every other plugin that made Hyper freeze would just make it hang with high cpu and Hyper would just remain stuck).

**Comment by andrewbanchich** [comment]
@stereokai Any update on this? Will this be fixed soon? I'd love to use it on Windows but it's not working for me either.

**Comment by henrikdahl** [comment]
@andrewbanchich I've been on a long vacation in the Caribbean so I've lacked time. But I'm gonna catch up with every issue including this. I was close to pushing a fix before I went ✌️

**Comment by andrewbanchich** [comment]
@henrikdahl Thank you!

**Comment by henrikdahl** [comment]
So I've tried multiple methods and the only one that ended up partially working was relying on titles but it was unreliable and afaik Windows doesn't even show the cwd in the title on most setups anyways.

I heard Hyper might expose a session value for CWD so I'll wait for that.

If you got any other ideas, please let me know. I tried all I can think of ✌️

**Comment by dougd** [comment]
See my PR #53 for another attempt at getting the cwd on win32. This again is a work around until it is properly supported by Hyper.
