### ISSUE TITLE
Allow customizing bg/fg colors based on cwd

### ISSUE THREAD

**Issue by derekr** [henrikdahl/hyper-statusline#41]
I like status line because I can keep my prompt small, but sometimes I forget what directory I'm in. It's simple enough to glance down and read the path, but it might be cool to color code the bar based on cwd (or any arbitrary condition via a configuration callback?). Maybe even color the git branch portion separately so you can glance and see if you're on the master branch.

Down to work on this and contribute upstream, but wanted to shop the idea around before digging in. Totes down to do this as a fork as well.

**Comment by henrikdahl** [comment]
Similar to powerline you mean? It would definitely have to be an option if implemented ✌️

**Comment by derekr** [comment]
Oh yeah for sure. Was curious if you'd even want it as an actual feature or if you wanted to keep status line simple.

**Comment by henrikdahl** [comment]
I'd sure like to keep `hyper-statusline` clean and simple but I don't mind elegant additions that match the existing base.

**Comment by henrikdahl** [comment]
Still open to merge this if anyone feel like contributing it. Closing for now because of inactivity ✌️
