### ISSUE TITLE
failed to load on windows

### ISSUE THREAD

**Issue by luisrudge** [henrikdahl/hyper-statusline#5]
![image](https://cloud.githubusercontent.com/assets/941075/21164619/6f6a7576-c181-11e6-9ee0-b4e69496e9cc.png)

**Comment by henrikdahl** [comment]
Wrote the code that fetches current CWD before Windows was on the map for Hyper. Currently relying on a UNIX exclusive command. I'm looking into viable alternatives right now. Pushing a fix soon! ✌️

**Comment by luisrudge** [comment]
maybe using https://www.npmjs.com/package/cwd?

**Comment by luisrudge** [comment]
I'm giving this a shot :)

**Comment by luisrudge** [comment]
yeah.. couldn't make this work on windows 😭

**Comment by henrikdahl** [comment]
No worries, I'm on it! Expect an update soon. ✌️

**Comment by Naramsim** [comment]
@luisrudge That means that in your ./hyper_plugins/node_modules `hyper-statusline` does not exist.
You can `npm i hyper-statusline` in that folder, and the plugin will load. However, it does nothing 😭 

I think something is broken in Hyperterm itself.

**Comment by henrikdahl** [comment]
@luisrudge Mind trying the os-windows branch to see if CWD works for you on Windows? I still can't debug myself ✌️

**Comment by luisrudge** [comment]
Ops.. Just saw your comment @henrikdahl. I'll test now

**Comment by henrikdahl** [comment]
@luisrudge Still needs work but since I can't debug myself it would be helpful to get some feedback during the process. Ideally the images properly load now. New method for CWD fetching is a little flawed and needs improvement.

**Comment by luisrudge** [comment]
@henrikdahl ok. now it loads. But doesn't show up anything :(
![image](https://cloud.githubusercontent.com/assets/941075/21406074/dbb72348-c7b0-11e6-87f5-8f3aa2e4e4c2.png)

**Comment by henrikdahl** [comment]
@luisrudge Images are loading now, so that's an improvement. Seems the CWD method needs fixing. I'll look at it. Thanks ✌️
