### ISSUE TITLE
Git info not displaying in subfolder

### ISSUE THREAD

**Issue by inkubux** [henrikdahl/hyper-statusline#55]
The git repository detection is flawed.

My git repo does not have .git files in subfolder only in the main folder.

A better way to detect would be:

git rev-parse --is-inside-work-tree

**Comment by xeroxoid** [comment]
Same here. Great plugin by the way!

**Comment by aguzubiaga** [comment]
Same problem. Can I send a PR?

**Comment by henrikdahl** [comment]
@xeroxoid Thanks!

Merged, sorry for the delay ✌️

**Comment by mattdarveniza** [comment]
I literally just came here to raise this issue. Great timing 🎉
