### ISSUE TITLE
statusline got wrong color.

### ISSUE THREAD

**Issue by SidKwok** [henrikdahl/hyper-statusline#60]
this is my plugins
```js
 plugins: [
    "hyper-tabs-enhanced",
    "hyperlinks",
    "hyperterm-alternatescroll",
    "hyper-statusline",
    "hyper-dracula"
  ],
```

BUT it got a statusline like this:

<img width="704" alt="f9116a602b6ad8e5b0977696cd44cf72" src="https://user-images.githubusercontent.com/13268747/29955253-f3b5177a-8f10-11e7-8896-ecf4af702cd2.png">

hyper: 1.4.2

**Comment by SidKwok** [comment]
problem solved,
theme should be placed above statusline.
```
 plugins: [
    "hyper-dracula",
    "hyper-statusline"
  ],
```

**Comment by kajka** [comment]
This trick doesn't work for extensions that are being developed (local plugins) :(.

**Comment by henrikdahl** [comment]
This is more of a Hyper issue. Since `statusline` fetches colors from active theme, that theme needs to be loaded before it. That's the way Hyper handles plugins ✌️
