### ISSUE TITLE
Doesn't work well with long paths

### ISSUE THREAD

**Issue by markokajzer** [henrikdahl/hyper-statusline#7]
The plugin does not work with with long paths (Java project...). The path just overflows and one can't see the whole thing. It also pushes the git branch information out.

![Long Path](https://cloud.githubusercontent.com/assets/9379317/21187510/8dacbb5e-c25b-11e6-8050-065a5871aef9.png)

**Comment by henrikdahl** [comment]
@markokajzer What would be your preferred solution? Multiple lines? Shortening overflowing text with dots? Scrolling text? ✌️

**Comment by henrikdahl** [comment]
Just pushed an update that handles overflowing paths better.

- No longer pushes away git branch
- Spacing improved
- Shows ellipsis when text overflows
- Added title to path element, long hover to see full path when truncated

Let me know what you think ✌️

**Comment by markokajzer** [comment]
Good stuff! 🔥🔥🔥
