### ISSUE TITLE
Npm bug?

### ISSUE THREAD

**Issue by chaoky** [henrikdahl/hyper-statusline#71]
npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for hyper-statusline@1.7.4: wanted {"os":"!          win32","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm ERR! notsup Valid OS:    !win32
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   win32
npm ERR! notsup Actual Arch: x64

**Comment by henrikruscon** [comment]
Try now that Windows is a supported platform, it shouldn't throw that error anymore ✌️
