### ISSUE TITLE
Adjust opacity or contrast for current working directory

### ISSUE THREAD

**Issue by adlersantos** [henrikdahl/hyper-statusline#83]
Hi! I'd like to suggest the ability to adjust opacity or contrast for the font/foreground in relation to the background.

It's a bit difficult to read the current working directory given the default settings:

<img width="1271" alt="screen shot 2018-06-19 at 12 10 07 pm" src="https://user-images.githubusercontent.com/1208372/41609862-bd10ad4a-73b9-11e8-961b-8bb343a95839.png">

Thanks!

**Comment by ypresto** [comment]
FYI: You can disable transparency of footer.

```
    hyperStatusLine: {
      footerTransparent: false,
    },
```

**Comment by adlersantos** [comment]
@ypresto Thank you! It's more readable now
