### ISSUE TITLE
Can not install this plugin in Hyper 3.0.0-canary.8 (canary)

### ISSUE THREAD

**Issue by linonetwo** [henrikdahl/hyper-statusline#88]
<img width="346" alt="2019-02-14 5 43 45" src="https://user-images.githubusercontent.com/3746270/52778109-2f5bc000-3080-11e9-8eca-4d8b368490e2.png">

There is no additional information in devtool.

Remove hyper-statusline from plugin list, this error will gone.

---
works fine after full remove of all plugins and reinstall.

**Comment by j-f1** [comment]
Can you expand the notification by dragging down on the bottom of it to reveal the rest of the message? It could also be in the devtools.
