### ISSUE TITLE
japanese dir name is displayed unicode characters

### ISSUE THREAD

**Issue by ergofriend** [henrikdahl/hyper-statusline#93]
dir name
```
n_ネットワーク論3
```

displayed
```
\xe3\x83\x8d\xe3\x83\x83\xe3\x83\x88\xe3\x83\xaf\xe3\x83\xbc\xe3\x82\xaf\xe8\xab\x963
```

![image](https://user-images.githubusercontent.com/29725082/66795232-f5102e80-ef3e-11e9-969c-ae6a6ae8f3e5.png)

**Comment by EliasGcf** [comment]
I have the same issue.

Any solution?

**Comment by EliasGcf** [comment]
I FIND THE SOLUTION

```js
exec(
    `lsof -p ${pid} | awk '$4=="cwd"' | tr -s ' ' | cut -d ' ' -f9-`,
    { env: { ...process.env, LANG: 'pt_BR.UTF-8' } },
    (err, stdout) => {
    cwd = stdout.trim();
    setGit(cwd);
    },
);
```

You can edit the `LANG` to your language unicode. (http://itdoc.hitachi.co.jp/manuals/3021/3021335500e/PCAU0074.HTM)

Thanks, @birobirobiro, for your collaboration.
