### ISSUE TITLE
hyper-statusline causes significant lag in Hyper v3.1.0

### ISSUE THREAD

**Issue by mitchwd** [henrikdahl/hyper-statusline#96]
Hyper was automatically updated to the latest stable version, but the hyper-statusline plugin causes so much lag that it makes it unusable.

Disabling the hyper-statusline plugin immediately resolves the issue.

Note: Similar project, hyperline has the same issue: https://github.com/Hyperline/hyperline/issues/198

**Comment by tr1s** [comment]
Following this topic.

I have the same issue, disabling the plugin solves the lag for me as well.

**Comment by RenanSgorlom** [comment]
still happening for hyper 3.1.2

**Comment by JJJ** [comment]
Not happening in 3.3.0. Fixed upstream in Electron.
